apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-form-config
data:
  DATABASE_URL: jdbc:mysql://mysql-service:3306/registration_db
  DATABASE_USERNAME: your_username
  DATABASE_PASSWORD: your_password
  APP_PORT: "8080"
